version: 0.2

phases:
  install:
    commands:
      - npm install -g typescript
  build:
    commands:
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ls -l /root/.pyenv/shims/aws
      - ./aws/install --bin-dir /root/.pyenv/shims --install-dir /usr/local/aws-cli --update
      - tsc src/functions/test/index.ts
  post_build:
    commands:
      - aws --version
      - aws cloudformation package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket test-pipeline-repository
      - aws cloudformation deploy --template-file packaged.yaml --stack-name testFunction --capabilities CAPABILITY_IAM
artifacts:
  files:
    - packaged.yaml